[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
ci = ["github"]
installers = ["shell", "powershell"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-musl",
  "x86_64-pc-windows-msvc",
]
install-updater = true
checksum = "sha256"
